In [1]:
#importing pandas and numpy libraries

In [2]:
import pandas as pb

In [3]:
import numpy as np

In [4]:
# importing yes and no cases

In [5]:
data_yes= pb.read_csv('lifeinsh.csv')

In [6]:
data_yes.shape

(108534, 26)

In [7]:
data_yes

,CUSTOMER NAME,POLICY_No,ZONE_NAME,STATE_NAME,OCCP_CODE,MARITAL_STATUS,AREA_CATEGORY,GENDER,POLICY_OWNER_MOBILENO,BRTH_DT,...,PREMIUM_PAYING_TERM,AGE,CUST_RELATION_PERIOD,NO_OF_ACTIVE_FACILITIES,QAB_Mar24,QAB_Dec23,MAB_May24,MAB_Apr24,MAB_Mar24,Product_TARGET
0,C156193,P82828,Zone21,State12,OCC36,UNMAR,RURAL,M,Y,15-04-2000,...,10,24,2,2,3.756100e+02,2.502160e+03,70.09,5.598400e+02,9.626900e+02,TRADITIONAL PLAN
1,C142964,P85068,Zone21,State12,OCC36,MAR,RURAL,M,Y,26-05-1995,...,15,29,4,4,2.256250e+03,3.913120e+03,1623.21,1.051480e+03,1.419600e+03,TRADITIONAL PLAN
2,C56307,P85976,Zone21,State12,OCC36,UNMAR,RURAL,M,Y,15-01-1995,...,15,29,8,1,0.000000e+00,0.000000e+00,0.00,0.000000e+00,0.000000e+00,TRADITIONAL PLAN
3,C43067,P87329,Zone21,State12,OCC36,UNMAR,RURAL,M,Y,28-07-1994,...,15,30,10,1,2.573700e+02,7.245240e+03,3.24,3.759100e+02,2.131300e+02,TRADITIONAL PLAN
4,C130125,P89801,Zone8,State33,OCC16,UNMAR,URBAN,F,Y,09-03-1997,...,5,27,8,2,1.478391e+04,1.461901e+05,2105.09,5.810650e+03,1.960318e+04,TRADITIONAL PLAN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108529,C15939,P186048,Zone9,State11,OCC36,OTHER,SEMI-URBAN,M,Y,02-05-1967,...,5,57,19,1,1.137736e+08,1.214117e+08,93272734.14,1.053296e+08,1.135631e+08,ULIP PLAN
108530,C102362,P188905,Zone9,State8,OCC36,MAR,URBAN,F,Y,20-12-1971,...,10,52,11,4,1.041502e+05,1.182480e+05,205248.92,1.879313e+05,1.173014e+05,ULIP PLAN
108531,C79728,P188260,Zone9,State11,OCC36,MAR,SEMI-URBAN,M,Y,10-12-1984,...,10,40,14,5,1.377399e+05,1.140748e+04,68358.78,2.941657e+05,3.028530e+05,ULIP PLAN
108532,C26082,P190099,Zone9,State11,OCC36,OTHER,METRO,M,Y,10-10-1956,...,10,68,20,2,1.627490e+06,4.578002e+05,1100465.83,1.364765e+06,1.327778e+06,ULIP PLAN
108533,C123938,P190160,Zone9,State8,OCC23,MAR,METRO,F,Y,12-12-1990,...,10,34,11,2,7.277242e+04,3.311620e+04,115725.42,9.668006e+04,7.303548e+04,ULIP PLAN

In [8]:
data_no= pb.read_csv('noinsh.csv')

In [9]:
data_no.shape

(243739, 26)

In [10]:
data_no

,CUSTOMER NAME,POLICY_No,ZONE_NAME,STATE_NAME,OCCP_CODE,MARITAL_STATUS,AREA_CATEGORY,GENDER,POLICY_OWNER_MOBILENO,BRTH_DT,...,PREMIUM_PAYING_TERM,AGE,CUST_RELATION_PERIOD,NO_OF_ACTIVE_FACILITIES,QAB_Mar24,QAB_Dec23,MAB_May24,MAB_Apr24,MAB_Mar24,Product_TARGET
0,275499,NaN,Zone12,State1,OCC23,MAR,URBAN,F,1,01-01-1980,...,NaN,44,16,2,27241.44,NaN,32657.34,NaN,NaN,No
1,226532,NaN,Zone12,State1,OCC23,MAR,URBAN,F,1,01-01-1999,...,NaN,25,15,1,85777.23,NaN,86190.79,NaN,NaN,No
2,456185,NaN,Zone12,State1,OCC23,MAR,URBAN,F,1,01-07-1966,...,NaN,58,15,5,19839.90,NaN,6340.51,NaN,NaN,No
3,249227,NaN,Zone12,State1,OCC24,UNMAR,URBAN,M,1,27-06-1994,...,NaN,30,15,1,349112.05,NaN,270738.66,NaN,NaN,No
4,309591,NaN,Zone12,State1,OCC36,MAR,URBAN,M,1,01-06-1965,...,NaN,59,15,2,191414.82,NaN,173417.99,NaN,NaN,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243734,420708,NaN,Zone18,State9,OCC36,UNMAR,SEMI-URBAN,M,1,15-04-1994,...,NaN,30,1,2,23744.46,NaN,18104.49,NaN,NaN,No
243735,432387,NaN,Zone18,State9,OCC36,MAR,SEMI-URBAN,M,1,01-12-1982,...,NaN,42,1,2,29701.91,NaN,42725.21,NaN,NaN,No
243736,344171,NaN,Zone18,State9,OCC16,MAR,SEMI-URBAN,M,1,12-06-1987,...,NaN,37,1,2,8768.91,NaN,11469.43,NaN,NaN,No
243737,371732,NaN,Zone18,State9,OCC36,UNMAR,SEMI-URBAN,F,1,01-11-1985,...,NaN,39,1,3,8865.14,NaN,22138.16,NaN,NaN,No
243738,479019,NaN,Zone18,State9,OCC36,UNMAR,SEMI-URBAN,M,1,08-03-1981,...,NaN,43,1,2,47771.55,NaN,53309.17,NaN,NaN,No

In [11]:
# forming a complete dataframe including all the yes and no cases

In [12]:
complete = pb.concat([data_yes, data_no], ignore_index=True)

In [13]:
complete.shape

(352273, 26)

In [14]:
#binning of age values into groups of 10s

In [15]:
bins = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
labels = ['0-10', '11-20', '21-30', '31-40', '41-50', '51-60', '61-70', '71-80', '81-90', '91-100']

In [16]:
complete['Age Range'] = pb.cut(complete['AGE'], bins=bins, labels=labels, right=False)

In [17]:
# taking an age range of ages 31 to 60 only

In [18]:
new_age_range = ['31-40' , '41-50' ,'51-60']

In [19]:
complete = complete[complete['Age Range'].isin(new_age_range)]

In [20]:
# binning of values of QAB and MAB

In [21]:
bins =[0,5000, 10000, 50000, 100000, 500000, 1000000, 5000000, 10000000, 50000000, 100000000]
labels = ['0-5000','5000-10000', '10001-50000', '50001-100000', '100001- 500000', ' 500001-1000000', '1000001-5000000', '5000001-10000000', '10000001-50000000', '50000001-100000000']

In [22]:
complete ['qab Range'] = pb.cut(complete ['QAB_Mar24'], bins=bins, labels=labels, right=False)

In [23]:
complete ['mab Range'] = pb.cut(complete ['MAB_May24'], bins=bins, labels=labels, right=False)

In [24]:
# removing QAB,MAB values below 5000

In [25]:
new_qab_mab_range = ['5000-10000', '10001-50000', '50001-100000', '100001- 500000', ' 500001-1000000', '1000001-5000000', '5000001-10000000', '10000001-50000000', '50000001-100000000']

In [26]:
complete = complete[complete['qab Range'].isin(new_qab_mab_range)]

In [27]:
complete = complete[complete['mab Range'].isin(new_qab_mab_range)]

In [28]:
# dropping of unnecessary variables

In [29]:
complete = complete.drop(columns=['CUSTOMER NAME', 'POLICY_No' , 'BRTH_DT', 'EFFECTIVE_DATE', 'POLICY_STATUS', 'PREMIUM FREQUENCY','ANNUALIZED_PREMIUM',  'QAB_Mar24',
 'MAB_May24','SUM_ASSURED','TERM','PREMIUM_PAYING_TERM','AGE','QAB_Dec23','MAB_Apr24','MAB_Mar24', 'POLICY_OWNER_MOBILENO'])

In [30]:
# encoding the remaining variables

In [31]:
c=['ZONE_NAME' , 'STATE_NAME' , 'MARITAL_STATUS' , 'AREA_CATEGORY', 'GENDER' , 'OCCP_CODE', 'qab Range', 'mab Range' , 'Age Range']

In [32]:
complete_1= pb.get_dummies(complete,columns=c)

In [33]:
complete_1

,CUST_RELATION_PERIOD,NO_OF_ACTIVE_FACILITIES,Product_TARGET,ZONE_NAME_Zone1,ZONE_NAME_Zone10,ZONE_NAME_Zone11,ZONE_NAME_Zone12,ZONE_NAME_Zone13,ZONE_NAME_Zone14,ZONE_NAME_Zone15,...,Age Range_0-10,Age Range_11-20,Age Range_21-30,Age Range_31-40,Age Range_41-50,Age Range_51-60,Age Range_61-70,Age Range_71-80,Age Range_81-90,Age Range_91-100
7,16,4,TRADITIONAL PLAN,False,False,False,False,False,False,True,...,False,False,False,False,True,False,False,False,False,False
11,18,1,TRADITIONAL PLAN,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
14,2,2,TRADITIONAL PLAN,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
15,3,4,TRADITIONAL PLAN,False,False,False,False,False,False,True,...,False,False,False,True,False,False,False,False,False,False
17,9,6,TRADITIONAL PLAN,False,False,False,False,True,False,False,...,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352268,1,2,No,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
352269,1,2,No,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
352270,1,2,No,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
352271,1,3,No,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
352272,1,2,No,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False

In [34]:
# separating the no cases from the complete dataframe

In [35]:
data_no_1=complete_1[complete_1['Product_TARGET']=='No']

In [36]:
data_no_1

,CUST_RELATION_PERIOD,NO_OF_ACTIVE_FACILITIES,Product_TARGET,ZONE_NAME_Zone1,ZONE_NAME_Zone10,ZONE_NAME_Zone11,ZONE_NAME_Zone12,ZONE_NAME_Zone13,ZONE_NAME_Zone14,ZONE_NAME_Zone15,...,Age Range_0-10,Age Range_11-20,Age Range_21-30,Age Range_31-40,Age Range_41-50,Age Range_51-60,Age Range_61-70,Age Range_71-80,Age Range_81-90,Age Range_91-100
108534,16,2,No,False,False,False,True,False,False,False,...,False,False,False,False,True,False,False,False,False,False
108536,15,5,No,False,False,False,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
108537,15,1,No,False,False,False,True,False,False,False,...,False,False,False,True,False,False,False,False,False,False
108538,15,2,No,False,False,False,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
108539,15,2,No,False,False,False,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352268,1,2,No,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
352269,1,2,No,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
352270,1,2,No,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
352271,1,3,No,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
352272,1,2,No,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False

In [37]:
#separating the different product targets from the complete dataframe

In [38]:
data_yes_a=complete_1[complete_1['Product_TARGET']=='ANNUITY PLAN']

In [39]:
data_yes_b=complete_1[complete_1['Product_TARGET']=='TERM PLAN']

In [40]:
data_yes_c=complete_1[complete_1['Product_TARGET']=='TRADITIONAL PLAN']

In [41]:
data_yes_d=complete_1[complete_1['Product_TARGET']=='ULIP PLAN']

In [42]:
# combining all the product targets to form complete yes case data

In [43]:
data_yes_1 = pb.concat([data_yes_a,data_yes_b,data_yes_c,data_yes_d ], ignore_index=True)

In [44]:
data_yes_2= pb.concat([data_yes_a,data_yes_b,data_yes_c,data_yes_d ], ignore_index=True)

In [45]:
data_yes_2

,CUST_RELATION_PERIOD,NO_OF_ACTIVE_FACILITIES,Product_TARGET,ZONE_NAME_Zone1,ZONE_NAME_Zone10,ZONE_NAME_Zone11,ZONE_NAME_Zone12,ZONE_NAME_Zone13,ZONE_NAME_Zone14,ZONE_NAME_Zone15,...,Age Range_0-10,Age Range_11-20,Age Range_21-30,Age Range_31-40,Age Range_41-50,Age Range_51-60,Age Range_61-70,Age Range_71-80,Age Range_81-90,Age Range_91-100
0,15,1,ANNUITY PLAN,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
1,8,1,ANNUITY PLAN,False,False,False,False,False,False,True,...,False,False,False,False,True,False,False,False,False,False
2,10,1,ANNUITY PLAN,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
3,14,2,ANNUITY PLAN,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
4,19,1,ANNUITY PLAN,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54070,16,3,ULIP PLAN,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
54071,15,2,ULIP PLAN,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
54072,11,4,ULIP PLAN,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
54073,14,5,ULIP PLAN,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
54074,11,2,ULIP PLAN,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False

In [46]:
data_yes_1

,CUST_RELATION_PERIOD,NO_OF_ACTIVE_FACILITIES,Product_TARGET,ZONE_NAME_Zone1,ZONE_NAME_Zone10,ZONE_NAME_Zone11,ZONE_NAME_Zone12,ZONE_NAME_Zone13,ZONE_NAME_Zone14,ZONE_NAME_Zone15,...,Age Range_0-10,Age Range_11-20,Age Range_21-30,Age Range_31-40,Age Range_41-50,Age Range_51-60,Age Range_61-70,Age Range_71-80,Age Range_81-90,Age Range_91-100
0,15,1,ANNUITY PLAN,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
1,8,1,ANNUITY PLAN,False,False,False,False,False,False,True,...,False,False,False,False,True,False,False,False,False,False
2,10,1,ANNUITY PLAN,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
3,14,2,ANNUITY PLAN,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
4,19,1,ANNUITY PLAN,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54070,16,3,ULIP PLAN,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
54071,15,2,ULIP PLAN,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
54072,11,4,ULIP PLAN,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
54073,14,5,ULIP PLAN,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
54074,11,2,ULIP PLAN,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False

In [46]:
# changing all product targets to 'YES'

In [47]:
data_yes_1['Product_TARGET'] = data_yes_1['Product_TARGET'].str.replace('TRADITIONAL PLAN','YES')
data_yes_1['Product_TARGET'] = data_yes_1['Product_TARGET'].str.replace('ULIP PLAN','YES')
data_yes_1['Product_TARGET'] = data_yes_1['Product_TARGET'].str.replace('TERM PLAN','YES')
data_yes_1['Product_TARGET'] = data_yes_1['Product_TARGET'].str.replace('ANNUITY PLAN','YES')

In [48]:
# taking out equal number of no cases as the number of yes cases

In [49]:
data_no_2= data_no_1.sample(50000)

In [50]:
data_no_1

,CUST_RELATION_PERIOD,NO_OF_ACTIVE_FACILITIES,Product_TARGET,ZONE_NAME_Zone1,ZONE_NAME_Zone10,ZONE_NAME_Zone11,ZONE_NAME_Zone12,ZONE_NAME_Zone13,ZONE_NAME_Zone14,ZONE_NAME_Zone15,...,Age Range_0-10,Age Range_11-20,Age Range_21-30,Age Range_31-40,Age Range_41-50,Age Range_51-60,Age Range_61-70,Age Range_71-80,Age Range_81-90,Age Range_91-100
108534,16,2,No,False,False,False,True,False,False,False,...,False,False,False,False,True,False,False,False,False,False
108536,15,5,No,False,False,False,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
108537,15,1,No,False,False,False,True,False,False,False,...,False,False,False,True,False,False,False,False,False,False
108538,15,2,No,False,False,False,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
108539,15,2,No,False,False,False,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352268,1,2,No,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
352269,1,2,No,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
352270,1,2,No,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
352271,1,3,No,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
352272,1,2,No,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False

In [51]:
data_no_2

,CUST_RELATION_PERIOD,NO_OF_ACTIVE_FACILITIES,Product_TARGET,ZONE_NAME_Zone1,ZONE_NAME_Zone10,ZONE_NAME_Zone11,ZONE_NAME_Zone12,ZONE_NAME_Zone13,ZONE_NAME_Zone14,ZONE_NAME_Zone15,...,Age Range_0-10,Age Range_11-20,Age Range_21-30,Age Range_31-40,Age Range_41-50,Age Range_51-60,Age Range_61-70,Age Range_71-80,Age Range_81-90,Age Range_91-100
215304,19,4,No,False,False,False,False,True,False,False,...,False,False,False,False,True,False,False,False,False,False
323692,16,2,No,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
181576,1,2,No,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
305038,14,1,No,False,False,False,False,False,True,False,...,False,False,False,False,False,True,False,False,False,False
302820,16,8,No,False,False,False,False,False,True,False,...,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116006,20,1,No,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
146808,9,1,No,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
346153,11,3,No,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
158036,11,3,No,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
224323,7,2,No,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False

In [52]:
list(data_no_2.columns)

['CUST_RELATION_PERIOD',
 'NO_OF_ACTIVE_FACILITIES',
 'Product_TARGET',
 'ZONE_NAME_Zone1',
 'ZONE_NAME_Zone10',
 'ZONE_NAME_Zone11',
 'ZONE_NAME_Zone12',
 'ZONE_NAME_Zone13',
 'ZONE_NAME_Zone14',
 'ZONE_NAME_Zone15',
 'ZONE_NAME_Zone16',
 'ZONE_NAME_Zone17',
 'ZONE_NAME_Zone18',
 'ZONE_NAME_Zone19',
 'ZONE_NAME_Zone2',
 'ZONE_NAME_Zone20',
 'ZONE_NAME_Zone21',
 'ZONE_NAME_Zone22',
 'ZONE_NAME_Zone3',
 'ZONE_NAME_Zone4',
 'ZONE_NAME_Zone5',
 'ZONE_NAME_Zone6',
 'ZONE_NAME_Zone7',
 'ZONE_NAME_Zone8',
 'ZONE_NAME_Zone9',
 'STATE_NAME_State1',
 'STATE_NAME_State10',
 'STATE_NAME_State11',
 'STATE_NAME_State12',
 'STATE_NAME_State13',
 'STATE_NAME_State14',
 'STATE_NAME_State15',
 'STATE_NAME_State16',
 'STATE_NAME_State17',
 'STATE_NAME_State18',
 'STATE_NAME_State19',
 'STATE_NAME_State2',
 'STATE_NAME_State20',
 'STATE_NAME_State21',
 'STATE_NAME_State22',
 'STATE_NAME_State23',
 'STATE_NAME_State24',
 'STATE_NAME_State25',
 'STATE_NAME_State26',
 'STATE_NAME_State27',
 'STATE_NAME_State28',
 'STATE_NAME_State29',
 'STATE_NAME_State3',
 'STATE_NAME_State30',
 'STATE_NAME_State31',
 'STATE_NAME_State32',
 'STATE_NAME_State33',
 'STATE_NAME_State34',
 'STATE_NAME_State4',
 'STATE_NAME_State5',
 'STATE_NAME_State6',
 'STATE_NAME_State7',
 'STATE_NAME_State8',
 'STATE_NAME_State9',
 'MARITAL_STATUS_MAR       ',
 'MARITAL_STATUS_OTHER     ',
 'MARITAL_STATUS_UNMAR     ',
 'AREA_CATEGORY_METRO',
 'AREA_CATEGORY_RURAL',
 'AREA_CATEGORY_SEMI-URBAN',
 'AREA_CATEGORY_URBAN',
 'GENDER_F     ',
 'GENDER_M     ',
 'GENDER_O     ',
 'GENDER_T     ',
 'OCCP_CODE_OCC1',
 'OCCP_CODE_OCC10',
 'OCCP_CODE_OCC11',
 'OCCP_CODE_OCC12',
 'OCCP_CODE_OCC13',
 'OCCP_CODE_OCC14',
 'OCCP_CODE_OCC15',
 'OCCP_CODE_OCC16',
 'OCCP_CODE_OCC17',
 'OCCP_CODE_OCC19',
 'OCCP_CODE_OCC2',
 'OCCP_CODE_OCC20',
 'OCCP_CODE_OCC21',
 'OCCP_CODE_OCC22',
 'OCCP_CODE_OCC23',
 'OCCP_CODE_OCC24',
 'OCCP_CODE_OCC25',
 'OCCP_CODE_OCC27',
 'OCCP_CODE_OCC28',
 'OCCP_CODE_OCC29',
 'OCCP_CODE_OCC3',
 'OCCP_CODE_OCC30',
 'OCCP_CODE_OCC31',
 'OCCP_CODE_OCC32',
 'OCCP_CODE_OCC33',
 'OCCP_CODE_OCC34',
 'OCCP_CODE_OCC35',
 'OCCP_CODE_OCC36',
 'OCCP_CODE_OCC37',
 'OCCP_CODE_OCC38',
 'OCCP_CODE_OCC39',
 'OCCP_CODE_OCC4',
 'OCCP_CODE_OCC40',
 'OCCP_CODE_OCC41',
 'OCCP_CODE_OCC42',
 'OCCP_CODE_OCC43',
 'OCCP_CODE_OCC44',
 'OCCP_CODE_OCC45',
 'OCCP_CODE_OCC46',
 'OCCP_CODE_OCC47',
 'OCCP_CODE_OCC48',
 'OCCP_CODE_OCC49',
 'OCCP_CODE_OCC5',
 'OCCP_CODE_OCC50',
 'OCCP_CODE_OCC51',
 'OCCP_CODE_OCC52',
 'OCCP_CODE_OCC53',
 'OCCP_CODE_OCC54',
 'OCCP_CODE_OCC55',
 'OCCP_CODE_OCC56',
 'OCCP_CODE_OCC6',
 'OCCP_CODE_OCC7',
 'OCCP_CODE_OCC8',
 'OCCP_CODE_OCC9',
 'qab Range_0-5000',
 'qab Range_5000-10000',
 'qab Range_10001-50000',
 'qab Range_50001-100000',
 'qab Range_100001- 500000',
 'qab Range_ 500001-1000000',
 'qab Range_1000001-5000000',
 'qab Range_5000001-10000000',
 'qab Range_10000001-50000000',
 'qab Range_50000001-100000000',
 'mab Range_0-5000',
 'mab Range_5000-10000',
 'mab Range_10001-50000',
 'mab Range_50001-100000',
 'mab Range_100001- 500000',
 'mab Range_ 500001-1000000',
 'mab Range_1000001-5000000',
 'mab Range_5000001-10000000',
 'mab Range_10000001-50000000',
 'mab Range_50000001-100000000',
 'Age Range_0-10',
 'Age Range_11-20',
 'Age Range_21-30',
 'Age Range_31-40',
 'Age Range_41-50',
 'Age Range_51-60',
 'Age Range_61-70',
 'Age Range_71-80',
 'Age Range_81-90',
 'Age Range_91-100']

In [53]:
#concating equal number of yes cases and no cases into a new dataframe

In [54]:
full_data = pb.concat([data_yes_1, data_no_2], ignore_index=True)

In [55]:
full_data

,CUST_RELATION_PERIOD,NO_OF_ACTIVE_FACILITIES,Product_TARGET,ZONE_NAME_Zone1,ZONE_NAME_Zone10,ZONE_NAME_Zone11,ZONE_NAME_Zone12,ZONE_NAME_Zone13,ZONE_NAME_Zone14,ZONE_NAME_Zone15,...,Age Range_0-10,Age Range_11-20,Age Range_21-30,Age Range_31-40,Age Range_41-50,Age Range_51-60,Age Range_61-70,Age Range_71-80,Age Range_81-90,Age Range_91-100
0,15,1,YES,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
1,8,1,YES,False,False,False,False,False,False,True,...,False,False,False,False,True,False,False,False,False,False
2,10,1,YES,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
3,14,2,YES,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
4,19,1,YES,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104070,20,1,No,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
104071,9,1,No,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
104072,11,3,No,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
104073,11,3,No,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
104074,7,2,No,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False

In [56]:
# dropping NA values

In [57]:
full_data.dropna(inplace=True)

In [58]:
# splitting data into x and y and dividing into training and testing sets

In [59]:
x = full_data.drop('Product_TARGET' , axis=1)
y = full_data['Product_TARGET']
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [60]:
x_train

,CUST_RELATION_PERIOD,NO_OF_ACTIVE_FACILITIES,ZONE_NAME_Zone1,ZONE_NAME_Zone10,ZONE_NAME_Zone11,ZONE_NAME_Zone12,ZONE_NAME_Zone13,ZONE_NAME_Zone14,ZONE_NAME_Zone15,ZONE_NAME_Zone16,...,Age Range_0-10,Age Range_11-20,Age Range_21-30,Age Range_31-40,Age Range_41-50,Age Range_51-60,Age Range_61-70,Age Range_71-80,Age Range_81-90,Age Range_91-100
94681,15,2,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
39689,4,2,False,False,False,False,False,False,True,False,...,False,False,False,True,False,False,False,False,False,False
29516,17,1,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
53967,7,5,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
63878,15,1,False,False,False,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50057,12,14,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
98047,11,10,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
5192,11,1,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
77708,14,1,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
98539,16,2,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False

In [61]:
y_train

94681     No
39689    YES
29516    YES
53967    YES
63878     No
        ...
50057    YES
98047     No
5192     YES
77708     No
98539     No
Name: Product_TARGET, Length: 83260, dtype: object

In [62]:
# applying Decision Tree Model

In [63]:
from sklearn import tree

In [64]:
DT_model= tree.DecisionTreeClassifier()

In [65]:
# fitting

In [66]:
DT_model.fit(x_train,y_train)

DecisionTreeClassifier()

In [67]:
y_DT= DT_model.predict(x_test)

In [68]:
# Evalution of DT model

In [69]:
from sklearn.metrics import accuracy_score

In [70]:
accuracy_score(y_test, y_DT)

0.6654335815517656

In [71]:
from sklearn.metrics import classification_report

In [72]:
import matplotlib.pyplot as plt

In [73]:
classification_report(y_test,y_DT)

'              precision    recall  f1-score   support\n\n          No       0.65      0.66      0.65      9983\n         YES       0.68      0.67      0.68     10832\n\n    accuracy                           0.67     20815\n   macro avg       0.67      0.67      0.67     20815\nweighted avg       0.67      0.67      0.67     20815\n'

In [74]:
from sklearn.metrics import confusion_matrix

In [75]:
cm=confusion_matrix(y_test, y_DT)

In [76]:
cm

array([[6593, 3390],
       [3574, 7258]], dtype=int64)

In [77]:
# applying Random Forest Model

In [78]:
from sklearn.ensemble import RandomForestClassifier

In [79]:
RF_model= RandomForestClassifier(n_estimators=100,random_state=42)

In [80]:
# fitting in RF model

In [81]:
RF_model.fit(x_train,y_train)

RandomForestClassifier(random_state=42)

In [82]:
# making predictions

In [83]:
y_RF= RF_model.predict(x_test)

In [84]:
# Evaluation of Random Forest

In [85]:
from sklearn.metrics import classification_report

In [86]:
classification_report(y_test,y_RF)

'              precision    recall  f1-score   support\n\n          No       0.72      0.68      0.70      9983\n         YES       0.72      0.76      0.74     10832\n\n    accuracy                           0.72     20815\n   macro avg       0.72      0.72      0.72     20815\nweighted avg       0.72      0.72      0.72     20815\n'

In [87]:
from sklearn.metrics import confusion_matrix

In [88]:
cm1=confusion_matrix(y_test, y_RF)

In [89]:
cm1

array([[6742, 3241],
       [2560, 8272]], dtype=int64)

In [90]:
from sklearn.metrics import accuracy_score

In [91]:
accuracy_score(y_test, y_RF)

0.7213067499399471

In [92]:
# the final no case data that should be used to find leads should be the data in total no cases apart from the sample data which was extracted to be used in testing and training the model

In [93]:
# finding common rows in both the total no case data and the no case data to be removed

In [94]:
common_rows = data_no_1 .merge(data_no_2, on=[
'CUST_RELATION_PERIOD',
 'NO_OF_ACTIVE_FACILITIES',
 'Product_TARGET',
 'ZONE_NAME_Zone1',
 'ZONE_NAME_Zone10',
 'ZONE_NAME_Zone11',
 'ZONE_NAME_Zone12',
 'ZONE_NAME_Zone13',
 'ZONE_NAME_Zone14',
 'ZONE_NAME_Zone15',
 'ZONE_NAME_Zone16',
 'ZONE_NAME_Zone17',
 'ZONE_NAME_Zone18',
 'ZONE_NAME_Zone19',
 'ZONE_NAME_Zone2',
 'ZONE_NAME_Zone20',
 'ZONE_NAME_Zone21',
 'ZONE_NAME_Zone22',
 'ZONE_NAME_Zone3',
 'ZONE_NAME_Zone4',
 'ZONE_NAME_Zone5',
 'ZONE_NAME_Zone6',
 'ZONE_NAME_Zone7',
 'ZONE_NAME_Zone8',
 'ZONE_NAME_Zone9',
 'STATE_NAME_State1',
 'STATE_NAME_State10',
 'STATE_NAME_State11',
 'STATE_NAME_State12',
 'STATE_NAME_State13',
 'STATE_NAME_State14',
 'STATE_NAME_State15',
 'STATE_NAME_State16',
 'STATE_NAME_State17',
 'STATE_NAME_State18',
 'STATE_NAME_State19',
 'STATE_NAME_State2',
 'STATE_NAME_State20',
 'STATE_NAME_State21',
 'STATE_NAME_State22',
 'STATE_NAME_State23',
 'STATE_NAME_State24',
 'STATE_NAME_State25',
 'STATE_NAME_State26',
 'STATE_NAME_State27',
 'STATE_NAME_State28',
 'STATE_NAME_State29',
 'STATE_NAME_State3',
 'STATE_NAME_State30',
 'STATE_NAME_State31',
 'STATE_NAME_State32',
 'STATE_NAME_State33',
 'STATE_NAME_State34',
 'STATE_NAME_State4',
 'STATE_NAME_State5',
 'STATE_NAME_State6',
 'STATE_NAME_State7',
 'STATE_NAME_State8',
 'STATE_NAME_State9',
 'MARITAL_STATUS_MAR       ',
 'MARITAL_STATUS_OTHER     ',
 'MARITAL_STATUS_UNMAR     ',
 'AREA_CATEGORY_METRO',
 'AREA_CATEGORY_RURAL',
 'AREA_CATEGORY_SEMI-URBAN',
 'AREA_CATEGORY_URBAN',
 'GENDER_F     ',
 'GENDER_M     ',
 'GENDER_O     ',
 'GENDER_T     ',
 'OCCP_CODE_OCC1',
 'OCCP_CODE_OCC10',
 'OCCP_CODE_OCC11',
 'OCCP_CODE_OCC12',
 'OCCP_CODE_OCC13',
 'OCCP_CODE_OCC14',
 'OCCP_CODE_OCC15',
 'OCCP_CODE_OCC16',
 'OCCP_CODE_OCC17',
 'OCCP_CODE_OCC19',
 'OCCP_CODE_OCC2',
 'OCCP_CODE_OCC20',
 'OCCP_CODE_OCC21',
 'OCCP_CODE_OCC22',
 'OCCP_CODE_OCC23',
 'OCCP_CODE_OCC24',
 'OCCP_CODE_OCC25',
 'OCCP_CODE_OCC27',
 'OCCP_CODE_OCC28',
 'OCCP_CODE_OCC29',
 'OCCP_CODE_OCC3',
 'OCCP_CODE_OCC30',
 'OCCP_CODE_OCC31',
 'OCCP_CODE_OCC32',
 'OCCP_CODE_OCC33',
 'OCCP_CODE_OCC34',
 'OCCP_CODE_OCC35',
 'OCCP_CODE_OCC36',
 'OCCP_CODE_OCC37',
 'OCCP_CODE_OCC38',
 'OCCP_CODE_OCC39',
 'OCCP_CODE_OCC4',
 'OCCP_CODE_OCC40',
 'OCCP_CODE_OCC41',
 'OCCP_CODE_OCC42',
 'OCCP_CODE_OCC43',
 'OCCP_CODE_OCC44',
 'OCCP_CODE_OCC45',
 'OCCP_CODE_OCC46',
 'OCCP_CODE_OCC47',
 'OCCP_CODE_OCC48',
 'OCCP_CODE_OCC49',
 'OCCP_CODE_OCC5',
 'OCCP_CODE_OCC50',
 'OCCP_CODE_OCC51',
 'OCCP_CODE_OCC52',
 'OCCP_CODE_OCC53',
 'OCCP_CODE_OCC54',
 'OCCP_CODE_OCC55',
 'OCCP_CODE_OCC56',
 'OCCP_CODE_OCC6',
 'OCCP_CODE_OCC7',
 'OCCP_CODE_OCC8',
 'OCCP_CODE_OCC9',
 'qab Range_0-5000',
 'qab Range_5000-10000',
 'qab Range_10001-50000',
 'qab Range_50001-100000',
 'qab Range_100001- 500000',
 'qab Range_ 500001-1000000',
 'qab Range_1000001-5000000',
 'qab Range_5000001-10000000',
 'qab Range_10000001-50000000',
 'qab Range_50000001-100000000',
 'mab Range_0-5000',
 'mab Range_5000-10000',
 'mab Range_10001-50000',
 'mab Range_50001-100000',
 'mab Range_100001- 500000',
 'mab Range_ 500001-1000000',
 'mab Range_1000001-5000000',
 'mab Range_5000001-10000000',
 'mab Range_10000001-50000000',
 'mab Range_50000001-100000000',
 'Age Range_0-10',
 'Age Range_11-20',
 'Age Range_21-30',
 'Age Range_31-40',
 'Age Range_41-50',
 'Age Range_51-60',
 'Age Range_61-70',
 'Age Range_71-80',
 'Age Range_81-90',
 'Age Range_91-100'], how='inner')

In [95]:
# removing the common data

In [96]:
final_data = data_no_1[~data_no_1.apply(tuple, 1).isin(common_rows.apply(tuple, 1))]

In [97]:
final_data

,CUST_RELATION_PERIOD,NO_OF_ACTIVE_FACILITIES,Product_TARGET,ZONE_NAME_Zone1,ZONE_NAME_Zone10,ZONE_NAME_Zone11,ZONE_NAME_Zone12,ZONE_NAME_Zone13,ZONE_NAME_Zone14,ZONE_NAME_Zone15,...,Age Range_0-10,Age Range_11-20,Age Range_21-30,Age Range_31-40,Age Range_41-50,Age Range_51-60,Age Range_61-70,Age Range_71-80,Age Range_81-90,Age Range_91-100
108534,16,2,No,False,False,False,True,False,False,False,...,False,False,False,False,True,False,False,False,False,False
108536,15,5,No,False,False,False,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
108538,15,2,No,False,False,False,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
108539,15,2,No,False,False,False,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
108540,15,4,No,False,False,False,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352268,1,2,No,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
352269,1,2,No,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
352270,1,2,No,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
352271,1,3,No,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
352272,1,2,No,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False

In [98]:
final_data_1 = final_data.drop('Product_TARGET' , axis=1)

In [99]:
# predicting on the final data

In [100]:
predictions = RF_model.predict(final_data_1)

In [101]:
predictions

array(['No', 'No', 'No', ..., 'No', 'YES', 'YES'], dtype=object)

In [102]:
# combining the prediction on the data

In [103]:
newcolumn= np.array(predictions)

In [104]:
final_data_1['Product_target'] = newcolumn

In [105]:
final_data_1

,CUST_RELATION_PERIOD,NO_OF_ACTIVE_FACILITIES,ZONE_NAME_Zone1,ZONE_NAME_Zone10,ZONE_NAME_Zone11,ZONE_NAME_Zone12,ZONE_NAME_Zone13,ZONE_NAME_Zone14,ZONE_NAME_Zone15,ZONE_NAME_Zone16,...,Age Range_11-20,Age Range_21-30,Age Range_31-40,Age Range_41-50,Age Range_51-60,Age Range_61-70,Age Range_71-80,Age Range_81-90,Age Range_91-100,Product_target
108534,16,2,False,False,False,True,False,False,False,False,...,False,False,False,True,False,False,False,False,False,No
108536,15,5,False,False,False,True,False,False,False,False,...,False,False,False,False,True,False,False,False,False,No
108538,15,2,False,False,False,True,False,False,False,False,...,False,False,False,False,True,False,False,False,False,No
108539,15,2,False,False,False,True,False,False,False,False,...,False,False,False,False,True,False,False,False,False,No
108540,15,4,False,False,False,True,False,False,False,False,...,False,False,False,False,True,False,False,False,False,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352268,1,2,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,No
352269,1,2,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,No
352270,1,2,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,No
352271,1,3,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,YES
352272,1,2,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,YES

In [106]:
# calculating number of yes and no predictions

In [107]:
np.unique(final_data_1['Product_target'], return_counts=True)

(array(['No', 'YES'], dtype=object), array([96814, 52453], dtype=int64))

In [108]:
# extracting the leads

In [109]:
data_multiclass=final_data_1[final_data_1['Product_target']=='YES']

In [110]:
data_multiclass

,CUST_RELATION_PERIOD,NO_OF_ACTIVE_FACILITIES,ZONE_NAME_Zone1,ZONE_NAME_Zone10,ZONE_NAME_Zone11,ZONE_NAME_Zone12,ZONE_NAME_Zone13,ZONE_NAME_Zone14,ZONE_NAME_Zone15,ZONE_NAME_Zone16,...,Age Range_11-20,Age Range_21-30,Age Range_31-40,Age Range_41-50,Age Range_51-60,Age Range_61-70,Age Range_71-80,Age Range_81-90,Age Range_91-100,Product_target
108542,15,3,False,False,False,True,False,False,False,False,...,False,False,False,True,False,False,False,False,False,YES
108544,15,3,False,False,False,True,False,False,False,False,...,False,False,False,True,False,False,False,False,False,YES
108557,13,3,False,False,False,True,False,False,False,False,...,False,False,False,True,False,False,False,False,False,YES
108558,12,8,False,False,False,True,False,False,False,False,...,False,False,False,True,False,False,False,False,False,YES
108561,12,4,False,False,False,True,False,False,False,False,...,False,False,False,False,True,False,False,False,False,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352248,1,2,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,YES
352253,1,2,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,YES
352264,1,2,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,YES
352271,1,3,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,YES
352272,1,2,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,YES

In [111]:
data_multiclass.to_excel('output1.xlsx', index=False)

In [112]:
# MULTI CLASS CLASSIFICATION : for predicitng the kind of product to pitch

In [113]:
# writing down the yes case data with the product target

In [114]:
data_yes_2

,CUST_RELATION_PERIOD,NO_OF_ACTIVE_FACILITIES,Product_TARGET,ZONE_NAME_Zone1,ZONE_NAME_Zone10,ZONE_NAME_Zone11,ZONE_NAME_Zone12,ZONE_NAME_Zone13,ZONE_NAME_Zone14,ZONE_NAME_Zone15,...,Age Range_0-10,Age Range_11-20,Age Range_21-30,Age Range_31-40,Age Range_41-50,Age Range_51-60,Age Range_61-70,Age Range_71-80,Age Range_81-90,Age Range_91-100
0,15,1,ANNUITY PLAN,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
1,8,1,ANNUITY PLAN,False,False,False,False,False,False,True,...,False,False,False,False,True,False,False,False,False,False
2,10,1,ANNUITY PLAN,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
3,14,2,ANNUITY PLAN,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
4,19,1,ANNUITY PLAN,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54070,16,3,ULIP PLAN,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
54071,15,2,ULIP PLAN,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
54072,11,4,ULIP PLAN,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
54073,14,5,ULIP PLAN,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
54074,11,2,ULIP PLAN,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False

In [115]:
# training and testing on the yes case data

In [116]:
x =data_yes_2.drop('Product_TARGET' , axis=1)
y = data_yes_2['Product_TARGET']
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [117]:
x_train

,CUST_RELATION_PERIOD,NO_OF_ACTIVE_FACILITIES,ZONE_NAME_Zone1,ZONE_NAME_Zone10,ZONE_NAME_Zone11,ZONE_NAME_Zone12,ZONE_NAME_Zone13,ZONE_NAME_Zone14,ZONE_NAME_Zone15,ZONE_NAME_Zone16,...,Age Range_0-10,Age Range_11-20,Age Range_21-30,Age Range_31-40,Age Range_41-50,Age Range_51-60,Age Range_61-70,Age Range_71-80,Age Range_81-90,Age Range_91-100
46660,19,2,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
27220,6,4,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
6685,18,7,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
13407,11,3,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
25553,14,2,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50057,12,14,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
32511,16,6,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
5192,11,1,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
12172,18,2,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
33003,17,1,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False

In [118]:
y_train

46660           ULIP PLAN
27220    TRADITIONAL PLAN
6685     TRADITIONAL PLAN
13407    TRADITIONAL PLAN
25553    TRADITIONAL PLAN
               ...
50057           ULIP PLAN
32511    TRADITIONAL PLAN
5192     TRADITIONAL PLAN
12172    TRADITIONAL PLAN
33003    TRADITIONAL PLAN
Name: Product_TARGET, Length: 43260, dtype: object

In [119]:
# applying Random Forest Algorithm

In [120]:
from sklearn.ensemble import RandomForestClassifier

In [121]:
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 42)

In [122]:
# fitting

In [123]:
classifier.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=42)

In [124]:
y_pred = classifier.predict(x_test)

In [125]:
y_pred

array(['TRADITIONAL PLAN', 'TRADITIONAL PLAN', 'TRADITIONAL PLAN', ...,
       'TRADITIONAL PLAN', 'TRADITIONAL PLAN', 'TRADITIONAL PLAN'],
      dtype=object)

In [126]:
# evaluation

In [127]:
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

In [128]:
y_test = np.array(y_test).flatten()
y_pred = np.array(y_pred).flatten()

In [129]:
cm = confusion_matrix(y_test, y_pred)

In [130]:
cm

array([[   0,    0,   11,    4],
       [   1,    8,   71,    6],
       [   1,   15, 8114,  643],
       [   0,    2, 1658,  281]], dtype=int64)

In [131]:
from sklearn.metrics import accuracy_score

In [132]:
((accuracy_score(y_test, y_pred))*100).round(2)

77.7

In [133]:
from sklearn.metrics import precision_score

In [134]:
precision_score(y_test, y_pred, average = 'macro')

0.36106962291859435

In [135]:
from sklearn.metrics import classification_report

In [136]:
import matplotlib.pyplot as plt

In [137]:
classification_report(y_test, y_pred)

'                  precision    recall  f1-score   support\n\n    ANNUITY PLAN       0.00      0.00      0.00        15\n       TERM PLAN       0.32      0.09      0.14        86\nTRADITIONAL PLAN       0.82      0.92      0.87      8773\n       ULIP PLAN       0.30      0.14      0.20      1941\n\n        accuracy                           0.78     10815\n       macro avg       0.36      0.29      0.30     10815\n    weighted avg       0.72      0.78      0.74     10815\n'

In [138]:
data_multiclass_1 = data_multiclass.drop(columns=['Product_target'])

In [139]:
# making predictions

In [140]:
predictions = classifier.predict(data_multiclass_1)

In [141]:
predictions

array(['TRADITIONAL PLAN', 'TRADITIONAL PLAN', 'TRADITIONAL PLAN', ...,
       'TRADITIONAL PLAN', 'TRADITIONAL PLAN', 'TRADITIONAL PLAN'],
      dtype=object)

In [142]:
 # combining the predictions to initial data to get leads

In [143]:
newcolumn= np.array(predictions)

In [144]:
data_multiclass_1['Product_target'] = newcolumn

In [145]:
data_multiclass_1

,CUST_RELATION_PERIOD,NO_OF_ACTIVE_FACILITIES,ZONE_NAME_Zone1,ZONE_NAME_Zone10,ZONE_NAME_Zone11,ZONE_NAME_Zone12,ZONE_NAME_Zone13,ZONE_NAME_Zone14,ZONE_NAME_Zone15,ZONE_NAME_Zone16,...,Age Range_11-20,Age Range_21-30,Age Range_31-40,Age Range_41-50,Age Range_51-60,Age Range_61-70,Age Range_71-80,Age Range_81-90,Age Range_91-100,Product_target
108542,15,3,False,False,False,True,False,False,False,False,...,False,False,False,True,False,False,False,False,False,TRADITIONAL PLAN
108544,15,3,False,False,False,True,False,False,False,False,...,False,False,False,True,False,False,False,False,False,TRADITIONAL PLAN
108557,13,3,False,False,False,True,False,False,False,False,...,False,False,False,True,False,False,False,False,False,TRADITIONAL PLAN
108558,12,8,False,False,False,True,False,False,False,False,...,False,False,False,True,False,False,False,False,False,TRADITIONAL PLAN
108561,12,4,False,False,False,True,False,False,False,False,...,False,False,False,False,True,False,False,False,False,TRADITIONAL PLAN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352248,1,2,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,TRADITIONAL PLAN
352253,1,2,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,TRADITIONAL PLAN
352264,1,2,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,TRADITIONAL PLAN
352271,1,3,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,TRADITIONAL PLAN
352272,1,2,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,TRADITIONAL PLAN

In [146]:
#counting the number of leads per plan

In [147]:
np.unique(data_multiclass_1['Product_target'], return_counts=True)

(array(['ANNUITY PLAN', 'TERM PLAN', 'TRADITIONAL PLAN', 'ULIP PLAN'],
       dtype=object),
 array([   16,    68, 48650,  3719], dtype=int64))

In [148]:
data_multiclass_1.to_excel('output.xlsx', index=False)